id: P5489C353
initial_creation_type: input
source_metadata:
  title: Pawo Lerab Tsal Series
  language: en
  description: 'Texts by and about the eighteenth century treasure-revealer Pawo Lerab
    Tsal (dpa'' bo las rab rtsal) alias Cheyöl Rigdzin Chenmo (che yol rig ''dzin
    chen mo):'
  volume:
    2c08f2775dc4466ba049a9e7e53db96a:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Guru Rinpoche Prayers
created_at: '2022-03-01T01:15:08.512919'
last_modified_at: '2022-03-01T01:15:08.512926'
